name: hydroshoot
channels:
  - fredboudon
  - conda-forge
  - pvlib
dependencies:
  - python=3.8
  - alinea.caribu
  - alinea.astk
  - pvlib
  - pandas
  - numpy
  - scipy
  - sympy
  - jsonschema
  - matplotlib
  - pytz
  - arrow